// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabalhoTCC.Data;

#nullable disable

namespace TrabalhoTCC.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250626002915_terceiraMigracao")]
    partial class terceiraMigracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrabalhoTCC.Models.Acessibilidade", b =>
                {
                    b.Property<int>("idAcessibilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAcessibilidade"));

                    b.Property<bool>("alertaSonoro")
                        .HasColumnType("bit");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("modoContraste")
                        .HasColumnType("bit");

                    b.Property<string>("tamanhoFonte")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<bool>("vibração")
                        .HasColumnType("bit");

                    b.HasKey("idAcessibilidade");

                    b.ToTable("TB_ACESSIBILIDADE", (string)null);

                    b.HasData(
                        new
                        {
                            idAcessibilidade = 1,
                            alertaSonoro = false,
                            idUsuario = 1,
                            modoContraste = true,
                            tamanhoFonte = "45",
                            vibração = true
                        },
                        new
                        {
                            idAcessibilidade = 2,
                            alertaSonoro = true,
                            idUsuario = 2,
                            modoContraste = true,
                            tamanhoFonte = "45",
                            vibração = true
                        },
                        new
                        {
                            idAcessibilidade = 3,
                            alertaSonoro = true,
                            idUsuario = 3,
                            modoContraste = false,
                            tamanhoFonte = "45",
                            vibração = true
                        },
                        new
                        {
                            idAcessibilidade = 4,
                            alertaSonoro = true,
                            idUsuario = 4,
                            modoContraste = false,
                            tamanhoFonte = "45",
                            vibração = false
                        },
                        new
                        {
                            idAcessibilidade = 5,
                            alertaSonoro = true,
                            idUsuario = 5,
                            modoContraste = false,
                            tamanhoFonte = "45",
                            vibração = false
                        },
                        new
                        {
                            idAcessibilidade = 6,
                            alertaSonoro = true,
                            idUsuario = 6,
                            modoContraste = false,
                            tamanhoFonte = "45",
                            vibração = true
                        },
                        new
                        {
                            idAcessibilidade = 7,
                            alertaSonoro = true,
                            idUsuario = 7,
                            modoContraste = true,
                            tamanhoFonte = "45",
                            vibração = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
